<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Student_model extends CI_Model
{

    public $table = 'plug_customer';
    public $id = 'plug_customer_id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('plug_customer_id', $q);
	$this->db->or_like('plug_customer_name', $q);
	$this->db->or_like('plug_customer_last_name', $q);
	$this->db->or_like('plug_customer_ic', $q);
	$this->db->or_like('plug_customer_gender_meta', $q);
	$this->db->or_like('plug_customer_occupation', $q);
	$this->db->or_like('plug_customer_phone', $q);
	$this->db->or_like('plug_customer_email', $q);
	$this->db->or_like('plug_customer_marital_meta', $q);
	$this->db->or_like('plug_customer_height', $q);
	$this->db->or_like('plug_customer_weight', $q);
	$this->db->or_like('plug_customer_address', $q);
	$this->db->or_like('plug_customer_data', $q);
	$this->db->or_like('plug_customer_media', $q);
	$this->db->or_like('plug_customer_status', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('plug_customer_id', $q);
	$this->db->or_like('plug_customer_name', $q);
	$this->db->or_like('plug_customer_last_name', $q);
	$this->db->or_like('plug_customer_ic', $q);
	$this->db->or_like('plug_customer_gender_meta', $q);
	$this->db->or_like('plug_customer_occupation', $q);
	$this->db->or_like('plug_customer_phone', $q);
	$this->db->or_like('plug_customer_email', $q);
	$this->db->or_like('plug_customer_marital_meta', $q);
	$this->db->or_like('plug_customer_height', $q);
	$this->db->or_like('plug_customer_weight', $q);
	$this->db->or_like('plug_customer_address', $q);
	$this->db->or_like('plug_customer_data', $q);
	$this->db->or_like('plug_customer_media', $q);
	$this->db->or_like('plug_customer_status', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file student_model.php */
/* Location: ./application/models/student_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2023-01-12 17:27:27 */
/* http://harviacode.com */