<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Mod_groups_model extends CI_Model
{

    public $table = 'mod_groups';
    public $id = 'mod_groups_id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('mod_groups_id',(string)$q);
    	$this->db->or_like('mod_groups_name',(string)$q);
    	$this->db->or_like('mod_groups_key',(string)$q);
        /*
        if($q===null){
            
        }else{
            
        }
        
    	
    	$this->db->or_like('mod_groups_meta_type', $q);
    	$this->db->or_like('mod_groups_parent_id', $q);
    	$this->db->or_like('mod_groups_icon', $q);
    	$this->db->or_like('mod_groups_sqn', $q);
    	$this->db->or_like('mod_groups_enabled', $q);*/
    	//$this->db->join('mod_meta', 'mod_meta.mod_meta_id = mod_groups.mod_groups_id', 'left');
    	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('mod_groups_id', (string)$q);
    	$this->db->or_like('mod_groups_name', (string)$q);
    	$this->db->or_like('mod_groups_key', (string)$q);/*
    	$this->db->or_like('mod_groups_meta_type', $q);
    	$this->db->or_like('mod_groups_parent_id', $q);
    	$this->db->or_like('mod_groups_icon', $q);
    	$this->db->or_like('mod_groups_sqn', $q);
    	$this->db->or_like('mod_groups_enabled', $q);*/
    	$this->db->join('mod_meta', 'mod_meta.mod_meta_id = mod_groups.mod_groups_meta_type', 'left');
    	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }
    function get_group_by_meta($id){
        $this->db->select('mod_groups.mod_groups_id,mod_groups.mod_groups_name,mod_groups.mod_groups_parent_id');
        $this->db->join('mod_meta', 'mod_meta.mod_meta_id = mod_groups.mod_groups_meta_type', 'left');
        $this->db->where('mod_groups_meta_type',$id);
        
        // $this->db->from($this->table);
        return $this->db->get($this->table)->result_array();
    }
    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Mod_groups_model.php */
/* Location: ./application/models/Mod_groups_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2022-08-24 13:53:49 */
/* http://harviacode.com */