<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Mod_meta_child_model extends CI_Model
{

    public $table = 'mod_meta';
    public $id = 'mod_meta_id';
    public $order = 'ASC';

    function __construct(){
        parent::__construct();
    }

    // get all
    function get_all($q){
        $this->db->where('mod_meta_key',$q);
        $this->db->order_by('mod_meta_seqn', $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id){
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
    	
    	$this->db->select('mod_meta.*,COUNT(mod_meta_id) as mod_meta_count');
    	$this->db->group_by('mod_meta_key');
    	$this->db->from($this->table);
    	
    	$this->db->order_by('mod_meta_seqn', $this->order);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->select('mod_meta.*,COUNT(mod_meta_id) as mod_meta_count');

    	
    	$this->db->group_by('mod_meta_key');
    	
    	$this->db->limit($limit, $start);
    	
    	$this->db->order_by('mod_meta_seqn', $this->order);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data){
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data){
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id){
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Mod_meta_model.php */
/* Location: ./application/models/Mod_meta_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2022-08-22 14:10:22 */
/* http://harviacode.com */