<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Svm_history_model extends CI_Model
{

    public $table = 'plug_svm';
    public $id = 'plug_svm_id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('plug_svm_id', $q);
	$this->db->or_like('plug_svm_student_id', $q);
	$this->db->or_like('plug_svm_value', $q);
	$this->db->or_like('plug_svm_code', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('plug_svm_id', $q);
	$this->db->or_like('plug_svm_student_id', $q);
	$this->db->or_like('plug_svm_value', $q);
	$this->db->or_like('plug_svm_code', $q);
	
	    $this->db->join('plug_customer', 'plug_customer.plug_customer_id = plug_svm.plug_svm_student_id','left');
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }
    function get_total_merit_list(){
        $this->db->select('plug_customer.*,plug_svm.*,sum(plug_svm_value) as sum');
        $this->db->join('plug_customer', 'plug_customer.plug_customer_id = plug_svm.plug_svm_student_id','left');
        
        $this->db->group_by("plug_svm.plug_svm_student_id");
        $this->db->order_by("sum",'desc');
	//$this->db->limit($limit, $start);
        $query = $this->db->get('plug_svm');
        
        return $query->result();
    }

}

/* End of file Svm_history_model.php */
/* Location: ./application/models/Svm_history_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2023-01-12 17:45:58 */
/* http://harviacode.com */